### ISSUE TITLE
Create GUI to generate trimap

### ISSUE THREAD

**Issue by liquidmetal** [liquidmetal/Bayesian-Matting#1]
Setup a basic GUI that allows the user to input an initial tripmap.
- Left click is foreground
- Right click is background

**Comment by liquidmetal** [comment]
Generating a proper trimap automatically isn't an easy task. For now, I've added enough 'drawing' capabilities to draw a rough trimap manually. I might add proper trimap generation later.

**Comment by coolcgp** [comment]
Is your trimap generator done, sir?
